name: migrate
on:
  push:
    branches:
      - master
    paths:
      - 'database/**'
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials from github actions secrets
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Run Migrate CodeBuild
        uses: aws-actions/aws-codebuild-run-project@v1.0.3
        with:
          project-name: treasure-2020-b-migrate

      - name: workflow finished
        uses: 8398a7/action-slack@v3.6.1
        with:
          status: ${{ job.status }}
          fields: repo,commit,message,author,job,took,workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

      - name: workflow finished
        uses: 8398a7/action-slack@v3.6.1
        with:
          status: ${{ job.status }}
          fields: repo,commit,message,author,job,took,workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.EBIS_SLACK_WEBHOOK_URL }}
        if: always()

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%s%3N')"

      - name: deployment tracking
        env:
          NR_INSIGHTS_API_KEY: ${{ secrets.NR_INSIGHTS_API_KEY }}
        run: |
          curl -k -H "Content-Type: application/json" \
            -H "Api-Key: $NR_INSIGHTS_API_KEY" \
            -X POST https://metric-api.newrelic.com/metric/v1 \
            --data '[{ "metrics":[
              {
                "name": "deployment",
                "type": "gauge",
                "value": 1.0,
                "timestamp": ${{ steps.date.outputs.date }},
                "interval.ms": 1000,
                "attributes": {
                  "group": "treasure-2020-b",
                  "app": "migrate",
                  "status": "${{ job.status }}",
                  "user": "${{ github.actor }}"
                }
              }
            ]}]'
